name: ysh

on:
  workflow_dispatch:
  schedule:
    - cron: 0 20 * * 2,5
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - "start"
  # release:
  #   types: [published]

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: write # for release creation

    name: Build ${{matrix.target}}

    runs-on: ubuntu-latest

    if: github.event.repository.owner.id == github.event.sender.id || ! github.event.sender.id

    strategy:
      fail-fast: false
      # max-parallel: 2
      matrix:
        target: [lede-openclash-x64]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Date
        run: |
          date=$(date +%Y-%m-%d)
          echo "DATE=${date}" >> $GITHUB_ENV

      - name: Initialize environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          sudo -E rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d /usr/local/lib/android
          sudo -E apt-mark hold grub-efi-amd64-signed
          sudo -E apt update
          sudo -E apt -y purge azure-cli* docker* ghc* zulu* llvm* firefox google* dotnet* powershell* openjdk* mysql* php* mongodb* dotnet* moby* snap*
          sudo -E apt -y full-upgrade
          sudo -E apt -y install ack antlr3 aria2 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libreadline-dev libssl-dev libtool lrzsz mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pip python3-pyelftools libpython3-dev qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
          sudo -E systemctl daemon-reload
          sudo -E apt -y autoremove --purge
          sudo -E apt clean
          sudo -E timedatectl set-timezone "Asia/Shanghai"

      - name: Set git identity
        run: |
          git config --global user.email "22856212+alecthw@users.noreply.github.com"
          git config --global user.name "alecthw"

      - name: Load Settings.ini
        run: |
          source "${GITHUB_WORKSPACE}/user/${{matrix.target}}/settings.ini"
          echo "REPO_URL=${REPO_URL}"                           >> $GITHUB_ENV
          echo "REPO_BRANCH=${REPO_BRANCH}"                     >> $GITHUB_ENV
          echo "CONFIG_FILE=${CONFIG_FILE}"                     >> $GITHUB_ENV
          echo "UPLOAD_PACKAGES_DIR=${UPLOAD_PACKAGES_DIR}"     >> $GITHUB_ENV
          echo "UPLOAD_TARGETS_DIR=${UPLOAD_TARGETS_DIR}"       >> $GITHUB_ENV
          echo "UPLOAD_FIRMWARE=${UPLOAD_FIRMWARE}"             >> $GITHUB_ENV
          echo "UPLOAD_TO_ARTIFACTS=${UPLOAD_TO_ARTIFACTS}"     >> $GITHUB_ENV
          echo "WECHAT_NOTIFICATION=${WECHAT_NOTIFICATION}"     >> $GITHUB_ENV

      - name: Clone user config
        env:
          REPO_URL: https://${{github.actor}}:${{secrets.SUPER_TOKEN}}@github.com/alecthw/archive.git
        run: |
          git clone --depth=1 $REPO_URL
          rm -rf defconfig
          cp -rf archive/home/defconfig defconfig

      - name: Clone source code
        run: |
          git clone --depth=1 -b ${{env.REPO_BRANCH}} ${{env.REPO_URL}} openwrt

      - name: Apply patches
        run: |
          echo "Apply patches"
          if [ -n "$(ls -A "user/common/patches" 2>/dev/null)" ]; then
          (
            find "user/common/patches" -type f -name '*.patch' -print0 | sort -z | xargs -I % -t -0 -n 1 sh -c "cat '%'  | patch -d 'openwrt' -p0 --forward"
          )
          fi
          if [ -n "$(ls -A "user/${{matrix.target}}/patches" 2>/dev/null)" ]; then
          (
            find "user/${{matrix.target}}/patches" -type f -name '*.patch' -print0 | sort -z | xargs -I % -t -0 -n 1 sh -c "cat '%'  | patch -d 'openwrt' -p0 --forward"
          )
          fi

      - name: Update feeds
        run: cd openwrt && ./scripts/feeds update -a

      - name: Load custom script
        run: |
          echo "Apply files..."
          if [ -n "$(ls -A "user/common/files" 2>/dev/null)" ]; then
          (
            cp -rf user/common/files/* openwrt/package/base-files/files/
          )
          fi
          if [ -n "$(ls -A "user/${{matrix.target}}/files" 2>/dev/null)" ]; then
          (
            cp -rf user/${{matrix.target}}/files/* openwrt/package/base-files/files/
          )
          fi

          echo "Apply custom.sh"
          if [ -f "user/common/custom.sh" ]; then
          (
            cd openwrt
            /bin/bash "../user/common/custom.sh" ${{matrix.target}}
          )
          fi
          if [ -f "user/${{matrix.target}}/custom.sh" ]; then
          (
            cd openwrt
            /bin/bash "../user/${{matrix.target}}/custom.sh"
          )
          fi

      - name: Install feeds
        run: cd openwrt && ./scripts/feeds install -a

      - name: Load custom configuration
        run: |
          echo "Apply config.sh"
          if [ -f "user/common/config.sh" ]; then
          (
            cd openwrt
            /bin/bash "../user/common/config.sh" ${{matrix.target}}
          )
          fi

      - name: Modify hostname
        run: |
          cd openwrt
          sed -i "s/hostname='OpenWrt'/hostname='OpenWrt-ysh'/g" package/base-files/files/bin/config_generate

      - name: Copy build config
        id: config
        run: |
          cd openwrt
          cp ../user/${{matrix.target}}/${{env.CONFIG_FILE}} .config
          make defconfig

      - name: Download package
        id: package
        run: |
          cd openwrt
          make download -j8
          find dl -size -1024c -exec ls -l {} \;
          find dl -size -1024c -exec rm -f {} \;

      - name: Compile the firmware
        id: compile
        run: |
          cd openwrt
          echo -e "$(nproc) thread compile"
          make -j$(nproc) || make -j1 V=s
          echo "status=success" >> $GITHUB_OUTPUT

      - name: Pack packages_dir
        if: steps.compile.outputs.status == 'success'
        run: |
          cd openwrt/bin/packages/
          tar -cvf ${{matrix.target}}_packages.tar ./
          mv *.tar ..

      - name: Pack targets_dir
        if: steps.compile.outputs.status == 'success'
        run: |
          cd openwrt/bin/targets/
          tar -cvf ${{matrix.target}}_targets.tar ./
          mv *.tar ..

      - name: Assemble Firmware
        run: |
          rm -rf ./Firmware/
          mkdir -p ./Firmware/
          cp -f openwrt/.config ./Firmware/
          find openwrt/bin/targets/ -name "*sysupgrade*bin*" | xargs -i mv -f {} ./Firmware/
          find openwrt/bin/targets/ -name "*sysupgrade*img*" | xargs -i mv -f {} ./Firmware/
          find openwrt/bin/targets/ -name "*combined*img*" | xargs -i mv -f {} ./Firmware/
          find openwrt/bin/targets/ -name "*factory*img*" | xargs -i mv -f {} ./Firmware/
          find openwrt/bin/targets/ -name "*vmdk*" | xargs -i mv -f {} ./Firmware/
          cd ./Firmware
          zip -r -P '${{secrets.ZIP_PASSWD}}' ./${{matrix.target}}.zip ./*vmdk* .config

      - name: Upload packages directory
        if: env.UPLOAD_PACKAGES_DIR == 'true' && env.UPLOAD_TO_ARTIFACTS == 'true' && !cancelled()　&& steps.compile.outputs.status == 'success'
        uses: actions/upload-artifact@main
        with:
          name: OpenWrt_packages_${{matrix.target}}
          path: openwrt/bin/packages

      - name: Upload targets directory
        if: env.UPLOAD_TARGETS_DIR == 'true' && env.UPLOAD_TO_ARTIFACTS == 'true' && !cancelled() && steps.compile.outputs.status == 'success'
        uses: actions/upload-artifact@main
        with:
          name: OpenWrt_targets_${{matrix.target}}
          path: openwrt/bin/targets

      - name: Upload Firmware
        if: env.UPLOAD_FIRMWARE == 'true' && env.UPLOAD_TO_ARTIFACTS == 'true' && !cancelled() && steps.compile.outputs.status == 'success'
        uses: actions/upload-artifact@main
        with:
          name: OpenWrt_firmware_${{matrix.target}}
          path: ./Firmware/${{matrix.target}}.zip

      # - name: Upload to github private repo
      #   env:
      #     REPO_URL: https://${{ github.actor }}:${{ secrets.PERSONAL_TOKEN }}@github.com/alecthw/firmware.git
      #   run: |
      #     rm -rf firmware_repo
      #     git clone $REPO_URL firmware_repo
      #     cd firmware_repo
      #     rm -rf ${{matrix.target}}
      #     mkdir -p ${{matrix.target}}
      #     cp ../Firmware/*.vmdk* ${{matrix.target}}/
      #     cp ../Firmware/.config ${{matrix.target}}/
      #     git add .
      #     git commit -m "Add ${{matrix.target}} on ${{env.DATE}}"
      #     git push -f -u origin main

      - name: WeChat notification
        if: env.WECHAT_NOTIFICATION == 'true' && !cancelled() && steps.compile.outputs.status == 'success'
        run: curl https://sc.ftqq.com/${{secrets.SCKEY}}.send?text=${{matrix.target}}编译完成
